### ISSUE TITLE
11 - US0009 - AS A user I WANT any unassigned trainees to be added to the waiting list SO THAT it can be used for priority

### ISSUE THREAD

**Issue by joelfright** [kxrtiswithak/AcademySimulator#4]
### DoD

trainees added to end of waiting list when all centres are full

### Test

- all unassigned trainees are added to waiting list
- trainees are added to end of waiting list
- trainees are only added once

[link to the branch](/kxrtiswithak/AcademySimulator/tree/feature-addToWaitingList)

**Comment by kxrtiswithak** [comment]
[link to the branch](/kxrtiswithak/AcademySimulator/tree/feature-addToWaitingList)
